// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async modelsDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|models_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async soniqoModelDir(model: LocalModel) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|soniqo_model_dir", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelDownloaded(model: LocalModel) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|is_model_downloaded", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelDownloading(model: LocalModel) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|is_model_downloading", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(model: LocalModel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|download_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(model: LocalModel) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|cancel_download", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(model: LocalModel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|delete_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getServerForModel(model: LocalModel) : Promise<Result<ServerInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|get_server_for_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getServers() : Promise<Result<Partial<{ [key in ServerType]: ServerInfo }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|get_servers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startServer(model: LocalModel) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|start_server", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopServer(serverType: ServerType | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|stop_server", { serverType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSupportedModels() : Promise<Result<SttModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|list_supported_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectCustomModelPath(path: string) : Promise<Result<CustomSttModelInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|inspect_custom_model_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startServerForPath(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|start_server_for_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Welche Verhoerungen der Nachlauf verwerfen wuerde -- aus DERSELBEN
 * Entscheidung, die er spaeter faellt.
 * 
 * Bis zum 03.09.2026 stand daneben eine 962-zeilige TypeScript-Kopie der
 * deutschen Stoppwortliste. Sie verglich sich per Test gegen die Rust-Liste,
 * aber nur die WORTMENGE -- die beiden Normalisierer (`stopwords::normalize`
 * hier, eine handgeschriebene Schleife dort) waren unabhaengiger Code. Wer in
 * Rust an der Normalisierung dreht, haette die gelbe Warnung in den
 * Einstellungen still zur Luege gemacht, und der Test waere gruen geblieben.
 * 
 * Eine Kopie weniger ist eine Wahrheit mehr.
 */
async vocabularyRiskyAliases(terms: string[]) : Promise<Result<RiskyAlias[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|vocabulary_risky_aliases", { terms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sucht fehlende Woerterbuch-Eintraege in vorhandenen Transkripten.
 * 
 * Zwei Netze, beide ohne Sprachmodell (`anlg_vocabulary::proposals`):
 * Wiederkehr mit Schwankung ueber mehrere Gespraeche, und Klangvergleich
 * gegen Teilnehmer, Titel, Notiz und die Woerterbuchliste selbst.
 * 
 * Gibt VORSCHLAEGE zurueck und schreibt nichts. Der Befehl ist rein: er
 * bekommt die Gespraeche, die Liste und die schon verworfenen Paare herein
 * und haelt keinen Zustand -- dieselbe Bauart wie
 * [`vocabulary_risky_aliases`].
 */
async vocabularyProposals(sessions: ProposalScanSession[], terms: string[], dismissed: DismissedProposal[]) : Promise<Result<VocabularyProposal[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|vocabulary_proposals", { sessions, terms, dismissed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
downloadProgressPayload: DownloadProgressPayload
}>({
downloadProgressPayload: "plugin:local-stt:download-progress-payload"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Apple's Speech framework exposes a single on-device transcriber whose behavior is
 * selected by locale rather than by model, so this carries one variant.
 */
export type AppleSpeechModel = "apple-speech"
export type CustomSttModelFormat = "ggml"
export type CustomSttModelInfo = { path: string; name: string; sizeBytes: number; format: CustomSttModelFormat }
/**
 * Ein Paar, das ein Mensch schon einmal verworfen hat.
 */
export type DismissedProposal = { canonical: string; alias: string }
export type DownloadProgressPayload = { model: LocalModel; status: DownloadStatus }
export type DownloadStatus = { downloading: number } | "completed" | { failed: string }
export type GgufLlmModel = "Llama3p2_3bQ4" | "Gemma3_4bQ4" | "AnarlogLLM"
export type LocalModel = SoniqoModel | AppleSpeechModel | WhisperModel | GgufLlmModel
/**
 * Ein Gespraech, wie es in den Vorschlags-Lauf geht.
 * 
 * Die Oberflaeche liest die Woerter und den Kontext aus der Datenbank und
 * reicht sie herein -- das Plugin spricht bewusst nicht selbst mit der
 * Datenbank, genauso wie `vocabulary_risky_aliases` seine Liste bekommt statt
 * sie zu holen.
 */
export type ProposalScanSession = { sessionId: string; words: ProposalScanWord[]; 
/**
 * Teilnehmernamen, ganz ("Mads Verlin | nordwerk") -- aus der Sitzung
 * UND aus dem Kalendertermin. NUR Namen.
 */
contextNames: string[]; 
/**
 * Die Mailadressen der Teilnehmer, getrennt gefuehrt: sie liefern
 * ausschliesslich Immunitaet und nie ein Ersetzungsziel. Siehe
 * `anlg_vocabulary::ScanSession::context_emails`.
 */
contextEmails: string[]; 
/**
 * Der von Menschen geschriebene Kontext: Kalendertitel,
 * Kalenderbeschreibung, Notiz.
 */
contextText: string; 
/**
 * Der vom Modell erzeugte Sitzungstitel. Wird ausdruecklich NICHT als
 * Beleg genommen -- siehe `anlg_vocabulary::ScanSession`.
 */
generatedTitle: string }
export type ProposalScanWord = { text: string; 
/**
 * Die GEMESSENE Wortsicherheit -- `null` heisst "nicht gemessen", nicht
 * "sicher".
 */
measuredConfidence: number | null }
/**
 * Eine eingetragene Verhoerung, die der Nachlauf nicht anwendet, weil sie
 * selbst gewoehnliches Deutsch ist.
 */
export type RiskyAlias = { canonical: string; alias: string }
export type ServerInfo = { url: string | null; status: ServerStatus; model: LocalModel | null; custom_model_path: string | null }
export type ServerStatus = "unreachable" | "loading" | "ready"
export type ServerType = "internal"
export type SoniqoModel = "soniqo-parakeet-streaming" | "soniqo-parakeet-batch" | "soniqo-omnilingual" | "soniqo-qwen3-small" | "soniqo-qwen3-large"
export type SttModelInfo = { key: LocalModel; display_name: string; description: string; size_bytes: number | null; model_type: SttModelType; supports_realtime: boolean; recommended_memory_bytes: number }
export type SttModelType = "soniqo" | "appleSpeech" | "whispercpp"
/**
 * Ein Vorschlag -- KEINE Ersetzung. Erst wenn ein Mensch ihn annimmt, wird
 * daraus ein Woerterbuch-Alias.
 */
export type VocabularyProposal = { kind: VocabularyProposalKind; canonical: string; alias: string; occurrences: number; sessionIds: string[]; evidence: string; source: string }
export type VocabularyProposalKind = 
/**
 * Wiederkehr mit Schwankung ueber mehrere Gespraeche.
 */
"recurrence" | 
/**
 * Klingt wie ein Name aus dem Kontext des Gespraechs.
 */
"context"
export type WhisperModel = "QuantizedTiny" | "QuantizedTinyEn" | "QuantizedBase" | "QuantizedBaseEn" | "QuantizedSmall" | "QuantizedSmallEn" | "QuantizedLargeTurbo"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
