-- Mitschnitt-Fork: aus „Zahlen und Namen zur Gegenpruefung" wird
-- „Bitte gegenpruefen", und der Abschnitt zieht aus sieben Vorlagen in den
-- Rahmen (Entscheid 07.09.2026).
--
-- ANLASS, gemessen an einer Zwei-Stunden-Aufnahme mit vier Personen
-- (17.000 Woerter): der Abschnitt lieferte dort 154 Woerter
-- in acht Stichpunkten, darunter „Mitte Januar, zwei Jahre, vor zwei Wochen,
-- letzte Woche, fuenf Jahre, zehn Jahre, vier Jahre, zehn Jahre" und eine
-- Zeile mit fuenfundzwanzig Laendernamen. Das Urteil: „macht ja mal gar
-- keinen Sinn!" -- und er hat recht, „zehn Jahre" ohne Bezug kann niemand
-- gegenlesen. Zwei Tage vorher, an einem Zwanzig-Minuten-Gespraech, fand er
-- denselben Abschnitt „mega": dort standen „Tilli / Billi" und „Renneke /
-- Renecke / Reneke" nebeneinander, also Schreibvarianten desselben Namens.
-- DIESER Teil traegt; die stumpfe Aufzaehlung aller Zahlen und Orte waechst
-- mit der Gespraechslaenge und begraebt ihn.
--
-- WAS AN SEINE STELLE TRITT, steht im Rahmen unter „# Closing Section: What
-- To Double-Check" (crates/template-app/assets/enhance.system.md.jinja):
-- eine Liste der Stellen, an denen ein Irrtum eine HANDLUNG aendern wuerde,
-- mit drei Sorten Unsicherheit in einer einzigen Liste -- verhoert (Name,
-- Zahl, Variantenpaar), missverstanden (worauf sich eine Zahl bezieht, ob
-- etwas Entscheidung oder lautes Nachdenken war, zu welcher Aufgabe eine
-- Frist gehoert) und nicht zurechenbar (was gesagt wurde, aber nicht von
-- wem). Jeder Stichpunkt traegt seinen Bezug, sonst ist er so wertlos wie
-- die alte Liste. Die Liste waechst mit der ZAHL der unsicheren Stellen,
-- nie mit der Gespraechslaenge; ohne Treffer faellt sie ganz weg.
--
-- WARUM IN DEN RAHMEN und nicht in die sieben Vorlagen: der Text stand
-- siebenmal WORTGLEICH da (sechs davon bytegleich, `mitschnitt-standard`
-- in einer kuerzeren Fassung). Sieben Kopien driften; eine Stelle nicht.
-- Und im Rahmen gilt der Abschnitt auch fuer jede Vorlage, die man sich
-- morgen selbst anlegt, und ueberlebt einen Eintrag in
-- `auto_summary_prompt`. Dasselbe Verfahren und derselbe Grund wie beim
-- Schritt 20260904160000.
--
-- WAS BEWUSST NICHT GEBAUT WURDE, obwohl es naheliegt: die Liste sollte auf
-- der GEMESSENEN Wortsicherheit des Erkenners stehen (`metadata.confidence`,
-- seit 03.09. an jedem Wort). Sie erreicht den Zusammenfassungs-Pfad nicht --
-- `Segment` traegt nur Text, Sprecher und Zeitmarke -- und das Anschliessen
-- war vorbereitet. Die Messung hat es gekippt: bei GENAU den Namen, auf die
-- es ankam, war sich der Erkenner SICHER und lag trotzdem falsch. Tilli 0,985 ·
-- Ilka 0,992 · Talwiese 0,952 · Renneke 0,885 · Renecke 0,687 · Theory 0,664;
-- am Zwei-Stunden-Gespraech liegen 10 von 13 zu Recht gemeldeten
-- Namensvarianten ueber 0,60 (Nore 0,73 · Saage 0,75 · Pfahl 0,67 ·
-- Heidmanns 0,94). Ein Verhoerer, der ein plausibles Wort ergibt, bekommt
-- eine hohe Sicherheit -- das ist Bauart, keine schlechte Schwelle. Was der
-- Filter stattdessen faengt, sind gewoehnliche Woerter (Gold, Welt, Titel)
-- und folgenlose Verhoerer (Kunduso, Zwal, Centlebau). A/B ueber beide
-- Gespraeche: ohne die Kandidatenliste war das Ergebnis gleich gut, einmal
-- sogar besser. Die Verdrahtung ist deshalb wieder ausgebaut.
--
-- WAS GEAENDERT WIRD, IST GENAU DER AUSLIEFERUNGSZUSTAND. Jedes UPDATE
-- traegt seine Vorbedingung Feld fuer Feld (Titel, Beschreibung, Abschnitte)
-- so, wie der jeweilige Seed sie eingesetzt hat. Wer eine Vorlage bearbeitet
-- hat, behaelt seine Fassung unangetastet -- der Inhalt entscheidet, nie der
-- Zeitstempel ('created_at = updated_at' sieht wie „nie angefasst" aus, ist
-- es aber nicht: der Legacy-Vault-Import legt eine BEARBEITETE Vorlage unter
-- derselben ID neu an und setzt beide Zeitstempel in EINEM Statement).
-- 'pinned' und 'icon_json' stehen aus denselben Gruenden wie beim Schritt
-- 20260904160000 nicht in der Vorbedingung.
--
-- RUECKWEG: die alten Fassungen stehen im Wortlaut in den Vorbedingungen
-- unten. Ein UPDATE mit vertauschten Seiten stellt jede wieder her. Die
-- gewaehlte Standard-Vorlage fasst dieser Schritt nicht an: keine ID aendert
-- sich. Downgrade-sicher: nur Daten, keine Schemaaenderung.

UPDATE templates
SET sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Projektüberblick", "description": "Umfang, Ziel und Liefergegenstände, wie sie im Gespräch benannt wurden."}, {"title": "Beteiligte und Rollen", "description": "Wer mitarbeitet und wofür zuständig ist. Nenn eine Rolle nur, wo sie im Gespräch zugeordnet wurde."}, {"title": "Zeitplan und Meilensteine", "description": "Termine und Meilensteine, wie sie ausgesprochen wurden, ein Stichpunkt je Punkt."}, {"title": "Kommunikation", "description": "Wie und wie oft man sich abstimmt: Termine, Kanäle, Berichtswege."}, {"title": "Erfolgskriterien", "description": "Woran das Projekt gemessen wird. Nur Kriterien, auf die man sich im Gespräch bezogen hat, mit ihren Zahlen."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}]'
WHERE id = 'default-client-kickoff'
  AND title = 'Kunden-Kickoff'
  AND description = 'Für den Auftakt eines neuen Kundenprojekts. Der Schwerpunkt liegt auf Beteiligten, Zeitplan und Erfolgskriterien: wer macht was, bis wann, und woran wird am Ende gemessen.'
  AND sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Projektüberblick", "description": "Umfang, Ziel und Liefergegenstände, wie sie im Gespräch benannt wurden."}, {"title": "Beteiligte und Rollen", "description": "Wer mitarbeitet und wofür zuständig ist. Nenn eine Rolle nur, wo sie im Gespräch zugeordnet wurde."}, {"title": "Zeitplan und Meilensteine", "description": "Termine und Meilensteine, wie sie ausgesprochen wurden, ein Stichpunkt je Punkt."}, {"title": "Kommunikation", "description": "Wie und wie oft man sich abstimmt: Termine, Kanäle, Berichtswege."}, {"title": "Erfolgskriterien", "description": "Woran das Projekt gemessen wird. Nur Kriterien, auf die man sich im Gespräch bezogen hat, mit ihren Zahlen."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}, {"title": "Zahlen und Namen zur Gegenprüfung", "description": "Alle Zahlen, Beträge, Termine und Eigennamen aus dem Gespräch, so wie sie im Transkript stehen, als kurze Liste. Sie dienen dem Gegenprüfen, weil sich die Transkription verhören kann; nichts ergänzen, nichts runden. Schreibt das Transkript denselben Namen verschieden, nenn die Varianten nebeneinander, statt dich für eine zu entscheiden."}]';


UPDATE templates
SET sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Kernaussagen", "description": "Die tragenden Gedanken und Theorien, ein Stichpunkt je Gedanke."}, {"title": "Begriffe und Definitionen", "description": "Jeder erklärte Begriff mit seiner Definition, so wie sie gesagt wurde. Ein Stichpunkt je Begriff, Begriff zuerst."}, {"title": "Beispiele und Anwendungen", "description": "Die Beispiele, an denen die Begriffe erklärt wurden, jeweils mit dem Begriff, zu dem sie gehören."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}]'
WHERE id = 'default-lecture-notes'
  AND title = 'Vorlesungsnotizen'
  AND description = 'Für Vorlesungen, Vorträge und Schulungen. Der Schwerpunkt liegt auf Begriffen und Beispielen: die tragenden Gedanken, die Definitionen dazu und die Beispiele, an denen sie erklärt wurden.'
  AND sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Kernaussagen", "description": "Die tragenden Gedanken und Theorien, ein Stichpunkt je Gedanke."}, {"title": "Begriffe und Definitionen", "description": "Jeder erklärte Begriff mit seiner Definition, so wie sie gesagt wurde. Ein Stichpunkt je Begriff, Begriff zuerst."}, {"title": "Beispiele und Anwendungen", "description": "Die Beispiele, an denen die Begriffe erklärt wurden, jeweils mit dem Begriff, zu dem sie gehören."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}, {"title": "Zahlen und Namen zur Gegenprüfung", "description": "Alle Zahlen, Beträge, Termine und Eigennamen aus dem Gespräch, so wie sie im Transkript stehen, als kurze Liste. Sie dienen dem Gegenprüfen, weil sich die Transkription verhören kann; nichts ergänzen, nichts runden. Schreibt das Transkript denselben Namen verschieden, nenn die Varianten nebeneinander, statt dich für eine zu entscheiden."}]';


UPDATE templates
SET sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Seit dem letzten Mal", "description": "Was seit dem vorigen Gespräch passiert ist, ein Stichpunkt je Sache."}, {"title": "Erfolge und Hürden", "description": "Was gelungen ist und was im Weg stand, getrennt in einzelne Stichpunkte."}, {"title": "Ziele und Fortschritt", "description": "Die besprochenen Ziele und wo sie stehen. Nur Ziele, die im Gespräch wirklich vorkamen; ein Stichpunkt je Ziel, mit dem konkreten Stand."}, {"title": "Feedback", "description": "Rückmeldungen in beide Richtungen, mit Sprecher, wo die Zuordnung eindeutig ist. Lob und Kritik im Wortlaut der Sache, nicht geglättet."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}]'
WHERE id = 'default-one-on-one-meeting'
  AND title = '1:1-Gespräch'
  AND description = 'Für das regelmäßige Vieraugengespräch mit einem Teammitglied. Der Schwerpunkt liegt auf Zielen und Feedback: was seit dem letzten Mal passiert ist, wo es hakt, wie die Ziele stehen und was in beide Richtungen zurückgemeldet wurde.'
  AND sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Seit dem letzten Mal", "description": "Was seit dem vorigen Gespräch passiert ist, ein Stichpunkt je Sache."}, {"title": "Erfolge und Hürden", "description": "Was gelungen ist und was im Weg stand, getrennt in einzelne Stichpunkte."}, {"title": "Ziele und Fortschritt", "description": "Die besprochenen Ziele und wo sie stehen. Nur Ziele, die im Gespräch wirklich vorkamen; ein Stichpunkt je Ziel, mit dem konkreten Stand."}, {"title": "Feedback", "description": "Rückmeldungen in beide Richtungen, mit Sprecher, wo die Zuordnung eindeutig ist. Lob und Kritik im Wortlaut der Sache, nicht geglättet."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}, {"title": "Zahlen und Namen zur Gegenprüfung", "description": "Alle Zahlen, Beträge, Termine und Eigennamen aus dem Gespräch, so wie sie im Transkript stehen, als kurze Liste. Sie dienen dem Gegenprüfen, weil sich die Transkription verhören kann; nichts ergänzen, nichts runden. Schreibt das Transkript denselben Namen verschieden, nenn die Varianten nebeneinander, statt dich für eine zu entscheiden."}]';


UPDATE templates
SET sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Sprint-Ziel", "description": "Das Hauptziel dieses Sprints in einem oder zwei Stichpunkten, so wie es ausgesprochen wurde."}, {"title": "Sprint-Backlog", "description": "Die Stories und Arbeitspakete, auf die sich das Team festgelegt hat, mit ihren Schätzungen, wo welche fielen."}, {"title": "Kapazität und Verfügbarkeit", "description": "Wer wie viel Zeit hat, Urlaube, Abwesenheiten, genannte Zahlen."}, {"title": "Abhängigkeiten und Risiken", "description": "Was von außen kommen muss und was schiefgehen kann, ein Stichpunkt je Punkt."}, {"title": "Definition von fertig", "description": "Woran „fertig“ gemessen wird: Abnahmekriterien und Standards, wie sie besprochen wurden."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}]'
WHERE id = 'default-sprint-planning'
  AND title = 'Sprint-Planung'
  AND description = 'Für die Sprint-Planung im Entwicklungsteam. Der Schwerpunkt liegt auf Ziel, Kapazität und Definition von fertig: was der Sprint erreichen soll, wer wie viel Zeit hat und woran „fertig“ gemessen wird.'
  AND sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Sprint-Ziel", "description": "Das Hauptziel dieses Sprints in einem oder zwei Stichpunkten, so wie es ausgesprochen wurde."}, {"title": "Sprint-Backlog", "description": "Die Stories und Arbeitspakete, auf die sich das Team festgelegt hat, mit ihren Schätzungen, wo welche fielen."}, {"title": "Kapazität und Verfügbarkeit", "description": "Wer wie viel Zeit hat, Urlaube, Abwesenheiten, genannte Zahlen."}, {"title": "Abhängigkeiten und Risiken", "description": "Was von außen kommen muss und was schiefgehen kann, ein Stichpunkt je Punkt."}, {"title": "Definition von fertig", "description": "Woran „fertig“ gemessen wird: Abnahmekriterien und Standards, wie sie besprochen wurden."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}, {"title": "Zahlen und Namen zur Gegenprüfung", "description": "Alle Zahlen, Beträge, Termine und Eigennamen aus dem Gespräch, so wie sie im Transkript stehen, als kurze Liste. Sie dienen dem Gegenprüfen, weil sich die Transkription verhören kann; nichts ergänzen, nichts runden. Schreibt das Transkript denselben Namen verschieden, nenn die Varianten nebeneinander, statt dich für eine zu entscheiden."}]';


UPDATE templates
SET sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Was gut lief", "description": "Was funktioniert hat, ein Stichpunkt je Sache, mit dem konkreten Beleg aus dem Sprint."}, {"title": "Was nicht gut lief", "description": "Probleme und Reibung, ein Stichpunkt je Sache. Benenn sie so, wie sie im Gespräch benannt wurden, ohne sie zu entschärfen."}, {"title": "Was wir gelernt haben", "description": "Die Einsichten, die das Team ausgesprochen hat, getrennt von den Maßnahmen darunter."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}]'
WHERE id = 'default-sprint-retrospective'
  AND title = 'Sprint-Retrospektive'
  AND description = 'Für den Rückblick am Sprint-Ende. Der Schwerpunkt liegt auf dem Dreischritt: was gut lief, was nicht lief, was daraus gelernt wurde.'
  AND sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Was gut lief", "description": "Was funktioniert hat, ein Stichpunkt je Sache, mit dem konkreten Beleg aus dem Sprint."}, {"title": "Was nicht gut lief", "description": "Probleme und Reibung, ein Stichpunkt je Sache. Benenn sie so, wie sie im Gespräch benannt wurden, ohne sie zu entschärfen."}, {"title": "Was wir gelernt haben", "description": "Die Einsichten, die das Team ausgesprochen hat, getrennt von den Maßnahmen darunter."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}, {"title": "Zahlen und Namen zur Gegenprüfung", "description": "Alle Zahlen, Beträge, Termine und Eigennamen aus dem Gespräch, so wie sie im Transkript stehen, als kurze Liste. Sie dienen dem Gegenprüfen, weil sich die Transkription verhören kann; nichts ergänzen, nichts runden. Schreibt das Transkript denselben Namen verschieden, nenn die Varianten nebeneinander, statt dich für eine zu entscheiden."}]';


UPDATE templates
SET description = 'Sechs Abschnitte: TL;DR, Entscheidungen, Themen aus dem Gespräch statt fester Liste, Aufgaben als Tabelle mit Wer und Bis, offene Fragen, Zitate. Für Beratungs- und Projektgespräche, in denen hinterher zählt, wer was bis wann macht.',
    sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Entscheidungen", "description": "Was tatsächlich entschieden wurde, ein Stichpunkt je Entscheidung. Eine Entscheidung braucht jemanden, der sie getroffen und ausgesprochen hat. Eine Absicht, ein Plan, ein Wunsch, eine Erwartung oder ein Vorschlag, dem nur niemand widersprochen hat, ist KEINE Entscheidung; er gehört zu den Aufgaben oder nirgendwo hin."}, {"title": "Themen", "description": "Schreib KEINE Überschrift, die wörtlich „Themen“ heisst. Bau diesen Teil aus dem Gespräch selbst: eine eigene Überschrift je Thema, das wirklich besprochen wurde, benannt nach diesem Thema. Folge den echten Themen und ihrer Gewichtung, nie einer festen Liste; überspring, was nicht vorkam. Fass zusammen, was zusammengehört: lieber vier bis sechs tragende Überschriften als ein Dutzend feine. Eine Randnotiz bekommt keine eigene Überschrift, sondern einen Stichpunkt unter dem Thema, zu dem sie gehört. Eine Entscheidung, die oben schon steht, wird hier nicht noch einmal ausgeschrieben; hier steht nur, was zu ihr geführt hat. Jeder Inhalt gehört unter eine dieser Überschriften, nie ein Textblock ohne Überschrift darüber. Darunter Stichpunkte, nie Fliesstext: dieser Teil wird überflogen, nicht gelesen. Drei zusammenhängende Sätze in einem Absatz sind falsch, auch wenn jeder Satz darin stimmt -- zerleg sie in ihre einzelnen Punkte."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}, {"title": "Zitate", "description": "Ganz am Schluss: bis zu drei WÖRTLICHE Aussagen, Wort für Wort, nie umformuliert oder geglättet, die einen Kernpunkt des Gesprächs treffen, jeweils mit dem Sprecher, aber nur bei eindeutiger Zuordnung. Ist die Formulierung im Transkript verstümmelt, lass das Zitat weg, statt es zu reparieren."}]'
WHERE id = 'mitschnitt-kompakt'
  AND title = 'Mitschnitt Kompakt'
  AND description = 'Sieben Abschnitte: TL;DR, Entscheidungen, Themen aus dem Gespräch statt fester Liste, Aufgaben als Tabelle mit Wer und Bis, offene Fragen, Zahlen und Namen zur Gegenprüfung, Zitate. Für Beratungs- und Projektgespräche, in denen hinterher zählt, wer was bis wann macht.'
  AND sections_json = '[{"title": "TL;DR", "description": "Die drei bis fünf wichtigsten Punkte, Entscheidungen und Aufgaben zuerst, für jemanden mit dreißig Sekunden."}, {"title": "Entscheidungen", "description": "Was tatsächlich entschieden wurde, ein Stichpunkt je Entscheidung. Eine Entscheidung braucht jemanden, der sie getroffen und ausgesprochen hat. Eine Absicht, ein Plan, ein Wunsch, eine Erwartung oder ein Vorschlag, dem nur niemand widersprochen hat, ist KEINE Entscheidung; er gehört zu den Aufgaben oder nirgendwo hin."}, {"title": "Themen", "description": "Schreib KEINE Überschrift, die wörtlich „Themen“ heisst. Bau diesen Teil aus dem Gespräch selbst: eine eigene Überschrift je Thema, das wirklich besprochen wurde, benannt nach diesem Thema. Folge den echten Themen und ihrer Gewichtung, nie einer festen Liste; überspring, was nicht vorkam. Fass zusammen, was zusammengehört: lieber vier bis sechs tragende Überschriften als ein Dutzend feine. Eine Randnotiz bekommt keine eigene Überschrift, sondern einen Stichpunkt unter dem Thema, zu dem sie gehört. Eine Entscheidung, die oben schon steht, wird hier nicht noch einmal ausgeschrieben; hier steht nur, was zu ihr geführt hat. Jeder Inhalt gehört unter eine dieser Überschriften, nie ein Textblock ohne Überschrift darüber. Darunter Stichpunkte, nie Fliesstext: dieser Teil wird überflogen, nicht gelesen. Drei zusammenhängende Sätze in einem Absatz sind falsch, auch wenn jeder Satz darin stimmt -- zerleg sie in ihre einzelnen Punkte."}, {"title": "Aufgaben", "description": "Als Markdown-TABELLE mit genau diesen Spalten:\n\n| Aufgabe | Wer | Bis |\n|---|---|---|\n\nEine Zeile je Aufgabe. Schreib nie ein Pipe-Zeichen in eine Tabellenzelle, das bricht die Tabelle; formulier um oder ersetz es durch ein Komma."}, {"title": "Offene Fragen", "description": "Was angesprochen, aber nicht geklärt wurde, dazu jede Stelle, an der das Transkript widersprüchlich oder unverständlich war. Ein Stichpunkt je Frage."}, {"title": "Zahlen und Namen zur Gegenprüfung", "description": "Alle Zahlen, Beträge, Termine und Eigennamen aus dem Gespräch, so wie sie im Transkript stehen, als kurze Liste. Sie dienen dem Gegenprüfen, weil sich die Transkription verhören kann; nichts ergänzen, nichts runden. Schreibt das Transkript denselben Namen verschieden, nenn die Varianten nebeneinander, statt dich für eine zu entscheiden."}, {"title": "Zitate", "description": "Ganz am Schluss: bis zu drei WÖRTLICHE Aussagen, Wort für Wort, nie umformuliert oder geglättet, die einen Kernpunkt des Gesprächs treffen, jeweils mit dem Sprecher, aber nur bei eindeutiger Zuordnung. Ist die Formulierung im Transkript verstümmelt, lass das Zitat weg, statt es zu reparieren."}]';


UPDATE templates
SET description = 'Eigener Schnitt: Kurzfassung, Entscheidungen, Bälle, offene Fragen.',
    sections_json = '[{"title":"Kurzfassung","description":"Drei Sätze: worum ging es, was ist das Ergebnis, was passiert als Nächstes. Fließtext, keine Aufzählung."},{"title":"Entscheidungen","description":"Was wurde entschieden, je ein Stichpunkt, mit dem Grund, wenn er genannt wurde. Nur echte Entscheidungen, keine Vorschläge oder Ideen."},{"title":"Bälle","description":"Wer macht was bis wann. Ein Stichpunkt je Ball: Name · Aufgabe · Termin (oder ‚kein Termin genannt‘). Ohne klaren Verantwortlichen ist es kein Ball, sondern eine offene Frage."},{"title":"Offene Fragen","description":"Was unentschieden oder unklar blieb, und wer die Antwort schuldet."}]'
WHERE id = 'mitschnitt-standard'
  AND title = 'Mitschnitt Standard'
  AND description = 'Eigener Schnitt: Kurzfassung, Entscheidungen, Bälle, offene Fragen, Zahlen und Namen zur Gegenprüfung.'
  AND sections_json = '[{"title":"Kurzfassung","description":"Drei Sätze: worum ging es, was ist das Ergebnis, was passiert als Nächstes. Fließtext, keine Aufzählung."},{"title":"Entscheidungen","description":"Was wurde entschieden, je ein Stichpunkt, mit dem Grund, wenn er genannt wurde. Nur echte Entscheidungen, keine Vorschläge oder Ideen."},{"title":"Bälle","description":"Wer macht was bis wann. Ein Stichpunkt je Ball: Name · Aufgabe · Termin (oder ‚kein Termin genannt‘). Ohne klaren Verantwortlichen ist es kein Ball, sondern eine offene Frage."},{"title":"Offene Fragen","description":"Was unentschieden oder unklar blieb, und wer die Antwort schuldet."},{"title":"Zahlen und Namen zur Gegenprüfung","description":"Alle Zahlen, Beträge, Termine und Eigennamen aus dem Gespräch, so wie sie im Transkript stehen, als kurze Liste. Sie dienen dem Gegenprüfen, weil sich die Transkription verhören kann; nichts ergänzen, nichts runden."}]';
