// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getOnboardingNeeded() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_onboarding_needed") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOnboardingNeeded(v: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_onboarding_needed", { v }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDismissedToasts() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dismissed_toasts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDismissedToasts(v: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_dismissed_toasts", { v }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEnv(key: string) : Promise<string> {
    return await TAURI_INVOKE("get_env", { key });
},
async showDevtool() : Promise<boolean> {
    return await TAURI_INVOKE("show_devtool");
},
async isAppStoreBuild() : Promise<boolean> {
    return await TAURI_INVOKE("is_app_store_build");
},
async completeAppExit() : Promise<void> {
    await TAURI_INVOKE("complete_app_exit");
},
async getTinybaseValues() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tinybase_values") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPinnedTabs() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pinned_tabs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPinnedTabs(v: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_pinned_tabs", { v }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecentlyOpenedSessions() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recently_opened_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setRecentlyOpenedSessions(v: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_recently_opened_sessions", { v }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkEmbeddedCli() : Promise<Result<EmbeddedCliStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_embedded_cli") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installEmbeddedCli() : Promise<Result<EmbeddedCliStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_embedded_cli") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkillAgents() : Promise<Result<SkillAgentStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skill_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installAgentSkill(agent: SkillAgent) : Promise<Result<SkillAgentStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_agent_skill", { agent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSettingsBundle(path: string, payload: string, includesSecrets: boolean, password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_settings_bundle", { path, payload, includesSecrets, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectSettingsBundle(path: string) : Promise<Result<BundleInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_settings_bundle", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readSettingsBundle(path: string, password: string | null) : Promise<Result<OpenedBundle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_settings_bundle", { path, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The folder this meeting lives in for a person.
 * 
 * Mitschnitt-Fork (F16b). Every "Show in Finder" resolves through here rather
 * than through `sessionDir`, which points into `sessions/<uuid>` -- a folder
 * with a uuid for a name and no transcript in it.
 * 
 * Returns `null` while the meeting has not been mirrored yet (the watcher runs
 * a moment behind a brand new session). The caller decides what to say; opening
 * the machine room instead would quietly reintroduce the second place.
 */
async mirrorSessionFolder(sessionId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mirror_session_folder", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The folder the readable copies currently live in.
 */
async mirrorRoot() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mirror_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Changes where the readable folders live: moves them and records the choice.
 * 
 * **One command, one writer.** This used to be two steps -- Rust moved the
 * folders, then the frontend wrote the setting -- and the gap between them was
 * long enough to matter: an app that died in it, or a watcher pass that ran
 * through it, put the old place back into use while the meetings were already
 * at the new one. The setting is now written here, under the same hold as the
 * move (see [`MirrorGate`]), so there is no moment in which the two disagree.
 * 
 * The setting is written only when every folder arrived. `move_root` moves all
 * of them or none, so refusing to switch on a failure leaves the meetings and
 * the app together at the old place, and the person can try again.
 * 
 * `new_root` empty means "back to the default place".
 */
async mirrorMoveRoot(newRoot: string) : Promise<Result<MirrorMoveReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mirror_move_root", { newRoot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the recording from the meeting folder, for a deletion the person
 * asked for.
 * 
 * Called next to the machine-room delete, never from the retention service:
 * see `anlg_mirror::forget_audio` for why that line is where it is.
 */
async mirrorForgetAudio(sessionId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mirror_forget_audio", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the whole meeting folder, once a deletion is final.
 */
async mirrorForgetSession(sessionId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mirror_forget_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Verschiebt den Speicherort samt Datenbank an einen neuen Ort.
 * 
 * Ersetzt `tauri-plugin-settings`s `moveVault`, das `app.db` nie mitnahm --
 * siehe den Modulkopf fuer die Begruendung.
 */
async moveVault(newPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_vault", { newPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BundleInfo = { version: number; created_at: string; app_version: string; includes_secrets: boolean; encrypted: boolean }
export type EmbeddedCliState = "installed" | "missing" | "conflict" | "unsupported" | "resource_missing"
export type EmbeddedCliStatus = { supported: boolean; commandName: string; installPath: string; state: EmbeddedCliState; details: string | null }
export type MirrorMoveFailure = { folder: string; reason: string }
/**
 * What a folder change did. Mirrors `anlg_mirror::MoveReport`, as a shape the
 * frontend can render.
 */
export type MirrorMoveReport = { moved: number; 
/**
 * Folder names that stayed at the old place, with the reason -- at most a
 * readable handful. Non-empty means a person has to be told: a
 * half-finished move that nobody sees is exactly the two-places problem
 * again.
 */
failed: MirrorMoveFailure[]; 
/**
 * How many failed altogether, which can be more than `failed` names.
 */
failedTotal: number }
export type OpenedBundle = { info: BundleInfo; 
/**
 * The payload as a JSON string. Kept as text so the shape stays the
 * frontend's business and a payload change needs no Rust change.
 */
payload: string }
export type SkillAgent = "claude_code" | "codex" | "cursor" | "opencode"
export type SkillAgentStatus = { agent: SkillAgent; displayName: string; detected: boolean; installed: boolean; skillPath: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
